#
# Macro file for the initialization phase of "NeutronSource.cc"
#
# Sets some default verbose
# and initializes the graphic.
#
/control/verbose 2
/run/verbose 2
#
/testhadr/det/setNbOfAbsor  6
/testhadr/det/setAbsor 1 AlMg3  0.02 cm
/testhadr/det/setAbsor 2 Alu  0.01 cm
/testhadr/det/setAbsor 3 B4C_enriched  0.0001 cm
/testhadr/det/setAbsor 4 SSteel  0.004 cm
/testhadr/det/setAbsor 5 AlMg3  0.05 cm
/testhadr/det/setAbsor 6 AlMg3  0.02 cm
/testhadr/det/setSizeY 100 mm
/testhadr/det/setSizeZ 60 mm
#
#
# To save the energy deposition in the slilcion slabs for dose calculations
# Set-> SetSiliconSlabs 1 and saveSiliconData 1 and saveFluxData 0
# To save the particles emerging from the world volume
# Set-> SetSiliconSlabs 0 and saveSiliconData 0 and saveFluxData 1
/testhadr/det/SetSiliconSlabs 1
/stepping/saveSiliconData 1
/stepping/saveFluxData 0
#
/run/initialize
#
# Open a viewer
/vis/open OGL
# This opens the default viewer
#
/vis/viewer/set/background white

# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume
#
# Specify view angle:
#/vis/viewer/set/viewpointThetaPhi 90. 0.
#
# Specify zoom value:
/vis/viewer/zoom 1.4
#
# Specify style (surface or wireframe):
#/vis/viewer/set/style wireframe
#/vis/viewer/set/style surface
# To get nice view
#/vis/geometry/set/visibility World 0 true
#
# Draw coordinate axes:
/vis/scene/add/axes 0 0 0 10 cm
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts false
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# Draw hits at end of event:
#/vis/scene/add/hits
#
# To draw only gammas:
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set neutron yellow
/vis/modeling/trajectories/drawByParticleID-0/set alpha blue
/vis/modeling/trajectories/drawByParticleID-0/set GenericIon blue
#
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate
#
#
# Axes, scale, etc.
#/vis/scene/add/scale   # Simple scale line
#/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.
/vis/scene/add/eventID # Drawn at end of event
/vis/scene/add/date    # Date stamp
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush
